# Generated by Django 4.1.4 on 2022-12-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_portafolio_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=150)),
                ('tipo_consulta', models.IntegerField(choices=[[0, 'Deseo asesoria'], [1, 'Deseo clases'], [2, 'Ayuda en mi codigo']])),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
