# Generated by Django 4.1.4 on 2022-12-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portafolio',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='tags',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='titulo',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
